name: oncoprint-otp-project
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - bedtools=2.16.2
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-annotationdbi=1.48.0
  - bioconductor-annotationfilter=1.10.0
  - bioconductor-biobase=2.46.0
  - bioconductor-biocfilecache=1.10.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biomart=2.42.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-biovizbase=1.34.0
  - bioconductor-bsgenome=1.54.0
  - bioconductor-complexheatmap=2.2.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-ensembldb=2.10.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicalignments=1.22.0
  - bioconductor-genomicfeatures=1.38.0
  - bioconductor-genomicranges=1.38.0
  - bioconductor-ggbio=1.34.0
  - bioconductor-graph=1.64.0
  - bioconductor-gtrellis=1.18.0
  - bioconductor-iranges=2.20.0
  - bioconductor-keggrest=1.26.0
  - bioconductor-organismdbi=1.28.0
  - bioconductor-pcamethods=1.78.0
  - bioconductor-protgenerics=1.18.0
  - bioconductor-rbgl=1.62.1
  - bioconductor-rhtslib=1.18.0
  - bioconductor-rsamtools=2.2.0
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-somaticsignatures=2.22.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-variantannotation=1.32.0
  - bioconductor-xvector=0.26.0
  - bioconductor-yapsa=1.12.0
  - bioconductor-zlibbioc=1.32.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - curl=7.83.1
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=3.1.1
  - icu=68.2
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsanitizer=9.4.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - make=4.3
  - ncurses=6.3
  - openssl=1.1.1o
  - pango=1.48.10
  - pcre=8.45
  - perl=5.26.2
  - perl-apache-test=1.40
  - perl-app-cpanminus=1.7044
  - perl-b=1.48
  - perl-b-hooks-endofscope=0.21
  - perl-base=2.23
  - perl-carp=1.38
  - perl-class-data-inheritable=0.08
  - perl-constant=1.33
  - perl-cpan-meta-check=0.014
  - perl-cpan-meta-requirements=2.140
  - perl-datetime=1.42
  - perl-datetime-locale=1.12
  - perl-datetime-timezone=2.09
  - perl-devel-stacktrace=2.04
  - perl-dist-checkconflicts=0.11
  - perl-eval-closure=0.14
  - perl-exception-class=1.44
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-getopt-long=2.50
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-module-implementation=0.09
  - perl-module-metadata=1.000036
  - perl-module-runtime=0.016
  - perl-namespace-autoclean=0.28
  - perl-namespace-clean=0.27
  - perl-package-stash=0.38
  - perl-package-stash-xs=0.28
  - perl-params-validationcompiler=0.23
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.52
  - perl-specio-exporter=0.36
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.14
  - perl-test-fatal=0.014
  - perl-try-tiny=0.30
  - perl-variable-magic=0.61
  - perl-version=0.9924
  - perl-warnings-register=1.03
  - perl-xsloader=0.24
  - pixman=0.40.0
  - pthread-stubs=0.4
  - r=3.6
  - r-acepack=1.4.1
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=3.6.3
  - r-base64enc=0.1_3
  - r-bh=1.75.0_0
  - r-bibtex=0.4.2.3
  - r-biocmanager=1.30.15
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.1
  - r-boot=1.3_28
  - r-brio=1.1.2
  - r-cachem=1.0.5
  - r-callr=3.7.0
  - r-checkmate=2.0.0
  - r-circlize=0.4.12
  - r-class=7.3_19
  - r-cli=2.5.0
  - r-clue=0.3_59
  - r-cluster=2.1.2
  - r-codetools=0.2_18
  - r-colorspace=2.0_1
  - r-corrplot=0.88
  - r-crayon=1.4.1
  - r-curl=4.3.1
  - r-data.table=1.14.0
  - r-dbi=1.1.1
  - r-dbplyr=2.1.1
  - r-dendextend=1.15.1
  - r-desc=1.3.0
  - r-dichromat=2.0_0
  - r-diffobj=0.3.4
  - r-digest=0.6.27
  - r-doparallel=1.0.16
  - r-dplyr=1.0.6
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-fansi=0.4.2
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-forcats=0.5.1
  - r-foreach=1.5.1
  - r-foreign=0.8_76
  - r-formatr=1.9
  - r-formula=1.2_4
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-generics=0.1.0
  - r-getoptlong=1.0.5
  - r-ggally=2.1.1
  - r-ggplot2=3.3.3
  - r-globaloptions=0.1.2
  - r-glue=1.4.2
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-highr=0.9
  - r-hmisc=4.5_0
  - r-hms=1.1.0
  - r-htmltable=2.2.1
  - r-htmltools=0.5.1.1
  - r-htmlwidgets=1.5.3
  - r-httr=1.4.2
  - r-irdisplay=1.0
  - r-irkernel=1.2
  - r-isoband=0.2.4
  - r-iterators=1.0.13
  - r-jpeg=0.1_8.1
  - r-jsonlite=1.7.2
  - r-kernsmooth=2.23_20
  - r-knitr=1.33
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-lattice=0.20_44
  - r-latticeextra=0.6_29
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.0
  - r-lsei=1.3_0
  - r-magrittr=2.0.1
  - r-markdown=1.1
  - r-mass=7.3_54
  - r-matrix=1.3_3
  - r-matrixstats=0.58.0
  - r-memoise=2.0.0
  - r-mgcv=1.8_35
  - r-mime=0.10
  - r-munsell=0.5.0
  - r-nlme=3.1_152
  - r-nmf=0.21.0
  - r-nnet=7.3_16
  - r-openssl=1.4.4
  - r-pbdzmq=0.3_5
  - r-pillar=1.6.1
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.1
  - r-pkgmaker=0.32.2
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-pmcmr=4.3
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.5.2
  - r-progress=1.2.2
  - r-proxy=0.4_25
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-r6=2.5.0
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-rcurl=1.98_1.3
  - r-recommended=3.6
  - r-registry=0.5_1
  - r-rematch2=2.1.2
  - r-repr=1.1.3
  - r-reshape=0.8.8
  - r-reshape2=1.4.4
  - r-rjson=0.2.20
  - r-rlang=0.4.11
  - r-rngtools=1.5
  - r-rpart=4.1_15
  - r-rprojroot=2.0.2
  - r-rsqlite=2.2.5
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-shape=1.4.6
  - r-snow=0.4_3
  - r-spatial=7.3_14
  - r-stringi=1.6.2
  - r-stringr=1.4.0
  - r-survival=3.2_11
  - r-sys=3.4
  - r-testthat=3.0.2
  - r-tibble=3.1.2
  - r-tidyr=1.1.3
  - r-tidyselect=1.1.1
  - r-utf8=1.2.1
  - r-uuid=0.1_4
  - r-vctrs=0.3.8
  - r-viridis=0.6.1
  - r-viridislite=0.4.0
  - r-waldo=0.2.5
  - r-withr=2.4.2
  - r-xfun=0.23
  - r-xml=3.99_0.3
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - readline=8.1.2
  - sed=4.8
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tktable=2.10
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
